const DISPLAY_ALERT = 'DISPLAY_ALERT';
const STOP_ALERT = 'STOP_ALERT';
const SET_ALERT_TIMEOUT_HANDLE = 'SET_ALERT_TIMEOUT_HANDLE';
const UPDATE_POSTS = 'UPDATE_POSTS';

export { DISPLAY_ALERT, STOP_ALERT, SET_ALERT_TIMEOUT_HANDLE, UPDATE_POSTS };
